<template>
  <div :class="$i18n.locale == 'ar' ? 'rtl' : ''" >
    <router-view v-if="loadedData" />
  </div>
</template>
<script>
export default {
  data() {
    return {
      loadedData: false,
    };
  },
  mounted() {
    this.loadedData = true;
  },
  methods: {
    onWindowLoad() {
      this.loadedData = true;
    },
  },
};
</script>

<style>
@font-face {
  font-family: "Museo Sans Rounded";
  src: url("/font.otf") format("opentype");
}

.animate-logo {
  -webkit-animation: rotate-in-center 1s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both infinite;
  animation: rotate-in-center 1s cubic-bezier(0.25, 0.46, 0.45, 0.94) both
    infinite;

  height: auto;
  width: 10rem;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-12-17 21:50:38
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-in-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-in-center {
  0% {
    -webkit-transform: rotate(-360deg);
    transform: rotate(-360deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
    opacity: 1;
  }
}
@keyframes rotate-in-center {
  0% {
    -webkit-transform: rotate(-360deg);
    transform: rotate(-360deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
    opacity: 1;
  }
}

#app {
  font-family: Museo Sans Rounded, Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#nav {
  padding: 30px;
}

#nav a {
  font-weight: bold;
  color: #2c3e50;
}

.rtl {
  direction: rtl;
}

#nav a.router-link-exact-active {
  color: #42b983;
}
</style>
